### ISSUE TITLE
Add a type for case-insensitive strings

### ISSUE THREAD

**Issue by chuwy** [axiomed/Http.lean#1]
In HTTP headers `Content-Type` and `content-type` must be equal. Currently we store header names as plain `String` which means the above property doesn't hold.

Tip: when implementing make sure that hashing works as expected in `HashMap CiString α`

Example in Scala: https://typelevel.org/case-insensitive/

**Comment by algebraic-sofia** [comment]
Closed by the PR made by @samueldurantes on `CaseInsensitive.lean`
